In [9]:
import pandas as pd
import numpy as num
import gmaps
from api_keys import gkey

In [18]:
file = "output/groupby_5_icons.csv"
df_weather_grouped = pd.read_csv(file)
df_weather_grouped

,Unnamed: 0,icon,Trip ID,precipIntensity,precipProbability,temperature,apparentTemperature,windSpeed,Trip Seconds,Trip Miles,Fare,Trip Total
0,0,clear,1979,0.000010,0.001546,47.332607,45.961789,2.797787,824.908999,3.034492,13.044669,15.255387
1,1,cloudy,1652,0.000216,0.028626,41.474104,38.812252,4.340969,760.361212,2.918711,11.790466,13.886344
2,2,partly cloudy,2681,0.000067,0.007411,52.761466,51.606927,3.555181,753.536940,2.738396,11.997307,14.004122
3,3,rain,508,0.034662,0.747894,54.773504,53.866752,3.941516,758.429134,3.889311,11.884213,13.892303
4,4,snow,22,0.007445,0.505909,33.234545,29.341364,5.102727,534.545455,1.082727,7.574545,8.506364

In [16]:
# df.loc[df['column_name'] == some_value]

df_clear = df_weather_grouped.loc[df_weather_grouped["icon"] == "clear"]
df_clear

,Unnamed: 0,icon,Trip ID,precipIntensity,precipProbability,temperature,apparentTemperature,windSpeed,Trip Seconds,Trip Miles,Fare,Trip Total
0,0,clear,1979,0.00001,0.001546,47.332607,45.961789,2.797787,824.908999,3.034492,13.044669,15.255387

In [11]:
gmaps.configure(api_key=gkey)
locations = df_merged[["Pickup Centroid Latitude", "Pickup Centroid Longitude"]].astype(float)

df_count = df_merged.groupby("Community Areas")["Trip ID"].count()
df_count = pd.DataFrame(df_count)

In [12]:
figure_layout = {
    "width": "900px",
    "height": "800px",
    "border": "1px solid black",
    "padding": "1px"
}

figure = gmaps.figure(layout=figure_layout)

heat_layer = gmaps.heatmap_layer(locations, weights=df_merged["Community Areas"], 
                                 dissipating=False, max_intensity=10000,
                                 point_radius = .003)


figure.add_layer(heat_layer)

# figure