In [11]:
import pandas as pd
import matplotlib as plt
import gmaps
from api_keys import gkey

file = "output/summary_df.csv"

df_summary = pd.read_csv(file)
# df_summary.head()

In [10]:
# df_summary["summary"].unique()

In [9]:
# df_summary.groupby("summary")["Trip ID"].count()

In [8]:
# df_summary.groupby("temperature")
# df_summary.dtypes
# df['new_col'] = df['First'].astype(str)
df_summary["New Column"] = df_summary["new time"].astype(str)

series_summary = pd.Series(df_summary["New Column"])
expanded_series_summary = series_summary.str.rsplit("-", expand=True)

df_expanded_date = pd.DataFrame(expanded_series_summary)
df_expanded_date.head()

df_summary_expanded_date = df_summary.join(df_expanded_date, how="outer")

# df = df.rename(columns={'oldName1': 'newName1', 'oldName2': 'newName2'})

df_summary_expanded_date = df_summary_expanded_date.rename(columns={"0": "Year", "1": "Month", "2": "Day"})
df_summary_expanded_date.head()

,Unnamed: 0,summary,new time,Trip ID,precipIntensity,precipProbability,temperature,apparentTemperature,windSpeed,New Column,0,1,2
0,0,Clear,2013-01-04,4,0.0,0.0,16.6825,7.5875,6.4325,2013-01-04,2013,01,04
1,1,Clear,2013-01-07,1,0.0,0.0,21.5800,15.0100,4.8400,2013-01-07,2013,01,07
2,2,Clear,2013-01-14,1,0.0,0.0,12.4300,7.1200,3.0300,2013-01-14,2013,01,14
3,3,Clear,2013-01-16,2,0.0,0.0,22.8950,18.8150,4.5750,2013-01-16,2013,01,16
4,4,Clear,2013-01-18,1,0.0,0.0,19.2600,19.2600,0.3900,2013-01-18,2013,01,18